version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings:DefaultConnection=Host=postgres;Port=5432;Database=printcenter;Username=printcenter;Password=printcenter
      - Secret=printcenterprintcenterprintcenterprintcenterprintc
    ports:
      - "5000:5000"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - /app/Logs
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - ApiUri=api:5000
    ports:
      - "8000:8000"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - /app/Logs
