name: build-and-test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore PrintCenter.sln
    - name: Install webassembly preview3
      run: dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview2.20160.5
    - name: Build
      run: dotnet build PrintCenter.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test PrintCenter.sln --no-restore --verbosity normal
